// REAL COLD STORAGE & PROCUREMENT CENTRES OF TAMIL NADU (136 FACILITIES)
// Extracted and geocoded directly from official Tamil Nadu Agri-Marketing & Cold Storage Registry

const DISTRICT_COORDS = {
  'Perumballur': { lat: 11.2333, lng: 78.8833 },
  'Ariyalur': { lat: 11.1401, lng: 79.0786 },
  'Chennai': { lat: 13.0827, lng: 80.2707 },
  'Coimbatore': { lat: 11.0168, lng: 76.9558 },
  'Cuddalore': { lat: 11.7480, lng: 79.7714 },
  'Dharmapuri': { lat: 12.1211, lng: 78.1582 },
  'Dindigul': { lat: 10.3673, lng: 77.9803 },
  'Erode': { lat: 11.3410, lng: 77.7172 },
  'Kancheepuram': { lat: 12.8342, lng: 79.7036 },
  'Kanyakumari': { lat: 8.0883, lng: 77.5385 },
  'Madurai': { lat: 9.9252, lng: 78.1198 },
  'Nilgiris': { lat: 11.4102, lng: 76.6950 },
  'Puthukottai': { lat: 10.3797, lng: 78.8202 },
  'Ramnathapuram': { lat: 9.3639, lng: 78.8395 },
  'Salem': { lat: 11.6643, lng: 78.1460 },
  'Theni': { lat: 10.0104, lng: 77.4768 },
  'Thiruvallur': { lat: 13.1432, lng: 79.9082 },
  'Tirunelveli': { lat: 8.7139, lng: 77.7567 },
  'Trichy': { lat: 10.7905, lng: 78.7047 },
  'Tuticorin': { lat: 8.7642, lng: 78.1348 },
  'Vellore': { lat: 12.9165, lng: 79.1325 },
  'Virudhnagar': { lat: 9.5680, lng: 77.9624 }
};

const rawData = [
  { sno: 1, name: "Raja cold storage SF No. 173/8E,Sendurai main road, Ariyalur-621 704", district: "Perumballur", capacity_mt: 3500, item: "multipurpose", sector: "Pvt" },
  { sno: 2, name: "Tamil Nadu Coop marketing Fed. Ltd, Basin bridge road, Chennai-600 012", district: "Chennai", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 3, name: "Department of racing Guindy,Chennai-32", district: "Chennai", capacity_mt: 12, item: "multipurpose", sector: "Pub" },
  { sno: 4, name: "Pukharaj Mohanlal 169, Govindappa Naik st, Chennai-1", district: "Chennai", capacity_mt: 25, item: "dry fruits", sector: "Pvt" },
  { sno: 5, name: "Maruthi Ice and cold storage 7, Abdul razak st, Saidapet, chennai-18", district: "Chennai", capacity_mt: 40, item: "fish,meat", sector: "Pvt" },
  { sno: 6, name: "Inter sea exports corporation 64,Habibulla road, T Nagar, chennai-17", district: "Chennai", capacity_mt: 250, item: "Marine products", sector: "Pvt" },
  { sno: 7, name: "Little top exports ltd 1, Kamaraj park st Royapuram Chennai-13", district: "Chennai", capacity_mt: 200, item: "marine products", sector: "Pvt" },
  { sno: 8, name: "TNFDC Ltd 67,Greams Road Chennai-6 CS at Adayar", district: "Chennai", capacity_mt: 50, item: "Marine products", sector: "Pub" },
  { sno: 9, name: "Spencer & Co 788, Mount road Chennai-2", district: "Chennai", capacity_mt: 102, item: "multipurpose", sector: "Pvt" },
  { sno: 10, name: "Tamil nadu coop Marketing federation Ltd,, 91,St.Mary's Road,Chennai18 (CS at Koyambedu market)", district: "Chennai", capacity_mt: 3000, item: "Multipurpose", sector: "Coop" },
  { sno: 11, name: "Himachal Cld stotage Ltd, Thiruvottiyur, Chennai-1", district: "Chennai", capacity_mt: 4000, item: "multipurpose", sector: "Pub" },
  { sno: 12, name: "Modern Ice Manufacturers 93, Dr. natesan road, Mylapore Chennai-4", district: "Chennai", capacity_mt: 25, item: "Fish, Meat", sector: "Pvt" },
  { sno: 13, name: "Sivitha ice creams p ltd, 92, P.H. road, Chennai-84", district: "Chennai", capacity_mt: 50, item: "ice creams", sector: "Pvt" },
  { sno: 14, name: "Asvini fisheries ltd, 10,K.B. Dasan Road, Chennai-18", district: "Chennai", capacity_mt: 200, item: "marine products", sector: "Pvt" },
  { sno: 15, name: "Madras Ice factory & CS 99, Sydenhams road, Chennai-600003", district: "Chennai", capacity_mt: 50, item: "Marine products", sector: "Pvt" },
  { sno: 16, name: "Kalyani marine exports 166,peters road Royapettah,Chennai-14", district: "Chennai", capacity_mt: 300, item: "Marine products", sector: "Pvt" },
  { sno: 17, name: "KPS Cold storage Ooty road, Mettupalayam-641 301 (unit-II)", district: "Coimbatore", capacity_mt: 1500, item: "multipurpose", sector: "Pvt" },
  { sno: 18, name: "Nahar Cold storage Thadagam road, Coimbatore-1", district: "Coimbatore", capacity_mt: 1500, item: "multipurpose", sector: "Pvt" },
  { sno: 19, name: "Tamil nadu coop milk marketing fed ltd, Coimbatore dary Coimbatore", district: "Coimbatore", capacity_mt: 280, item: "milk products", sector: "coop" },
  { sno: 20, name: "KPS Abdul Majeed & Co 10.Olylla st, Mettupalayam-641 301", district: "Coimbatore", capacity_mt: 2500, item: "multipurpose", sector: "Pvt" },
  { sno: 21, name: "Kwality ice creams P ltd E-47,Kurichi Ind.Estate Coimbatore-641 021", district: "Coimbatore", capacity_mt: 40, item: "ice creams", sector: "Pvt" },
  { sno: 22, name: "Abhirami cold storage P ltd Palaugarai Village Avinashi Taluk Coimbatore", district: "Coimbatore", capacity_mt: 1000, item: "multipurpose", sector: "Pvt" },
  { sno: 23, name: "Suvai foods Vaikalpalayam, Perur main road, Coimbatore-541 010", district: "Coimbatore", capacity_mt: 40, item: "ice creams", sector: "Pvt" },
  { sno: 24, name: "Nilgiri cold storage Ooty road Mettupalayam-641 301", district: "Coimbatore", capacity_mt: 3000, item: "multipurpose", sector: "Pvt" },
  { sno: 25, name: "AKS cold storage SF No. 956-57 Bhadrakaliamman koil Tekkampally village Mettupalayam-641 305", district: "Coimbatore", capacity_mt: 5400, item: "multipurpose", sector: "Pvt" },
  { sno: 26, name: "Kerala food packers Kinjampettai Cuddalore port-607 003 (closed)", district: "Cuddalore", capacity_mt: 100, item: "Marine products", sector: "Pvt", is_closed: true },
  { sno: 27, name: "George Maijo 112, Sonagat st, Cuddalore (closed)", district: "Cuddalore", capacity_mt: 25, item: "marine products", sector: "Pvt", is_closed: true },
  { sno: 28, name: "ASA cold storage Ameer estate,Azad nagar Krishnagiri-635 001", district: "Dharmapuri", capacity_mt: 5000, item: "multipurpose", sector: "Pvt" },
  { sno: 29, name: "Tamil nadu Coop milk marketing Fed. Ltd, Krishnagiri dairy Krishnagiri", district: "Dharmapuri", capacity_mt: 490, item: "milk products", sector: "Coop" },
  { sno: 30, name: "New Vennila cold storage 117A, Jettihalli post Dharmapuri- Dt", district: "Dharmapuri", capacity_mt: 3200, item: "multipurpose", sector: "Pvt" },
  { sno: 31, name: "R.R cold storage 140/A, Kattinayarapalli, Varathanpalli Road Krishnagiri- 634 001", district: "Dharmapuri", capacity_mt: 5000, item: "multipurpose", sector: "Pvt" },
  { sno: 32, name: "Brothers cold storage 65, Nalla Thambi st Krishnagiri (expansion)", district: "Dharmapuri", capacity_mt: 1400, item: "multipurpose", sector: "Pvt" },
  { sno: 33, name: "Jayalakhmi cold storage Krishnagiri", district: "Dharmapuri", capacity_mt: 750, item: "multipurpose", sector: "Pvt" },
  { sno: 34, name: "Vennila cold storage 25-A,Kaliappa Gounder st Mathikonpalayam Dharmapuri", district: "Dharmapuri", capacity_mt: 2500, item: "multipurpose", sector: "Pvt" },
  { sno: 35, name: "Brothers cold storage 65, Nalla thambi st, Krishnagiri-635 002", district: "Dharmapuri", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 36, name: "Ebenezar cold storage, Odanchatram Taluk, Dindigul", district: "Dindigul", capacity_mt: 1200, item: "multipurpose", sector: "Pvt" },
  { sno: 37, name: "Tamil Nadu Coop milk Marketing Fed Ltd, Dindigul dairy Dindigul", district: "Dindigul", capacity_mt: 38, item: "milk products", sector: "coop" },
  { sno: 38, name: "Avanam Pillayar cold storage P Ltd, 31-A, MVM Nagar, Dindigal- 624 004", district: "Dindigul", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 39, name: "Saravana cold storage 30/1 B1,Viralipatti Village Koovanoothu PO, Dindigul", district: "Dindigul", capacity_mt: 4000, item: "multipurpose", sector: "Pvt" },
  { sno: 40, name: "Nilgiri dairy farm ltd, Erode", district: "Erode", capacity_mt: 50, item: "milk products", sector: "Pvt" },
  { sno: 41, name: "Tamil nadu coop milk marketing fed. Ltd Erode dairy Erode", district: "Erode", capacity_mt: 602, item: "milk products", sector: "coop" },
  { sno: 42, name: "Thirumuruga cold storage Ltd, SIPCOT Ind. Estate, Perumdurai Erode (dt)", district: "Erode", capacity_mt: 5200, item: "multipurpose", sector: "pvt" },
  { sno: 43, name: "George maijo & Co, Plot.No.23, MGR road, Palavakkam, Chennai-41(closed)", district: "Kancheepuram", capacity_mt: 250, item: "Marine products", sector: "Pvt", is_closed: true },
  { sno: 44, name: "Westernfarm fresh P ltd 15/1-B1 Varadarajapuram Poonamallee Sriperumbudur", district: "Kancheepuram", capacity_mt: 2500, item: "fruits and vegetables", sector: "Pvt" },
  { sno: 45, name: "Abad Overseas P ltd, C/2, SIPCOT Ind. Estate, Irrungattukottai Chennau-602 105", district: "Kancheepuram", capacity_mt: 500, item: "Marine products", sector: "Pvt" },
  { sno: 46, name: "Aries exports P Ltd Kumaran nagar, Old Mahabalipuram road Chamacheri, Chennai-96", district: "Kancheepuram", capacity_mt: 100, item: "marine products", sector: "Pvt" },
  { sno: 47, name: "Devi marine exports ltd, 63/1, Muttukadu road, Chennai-41", district: "Kancheepuram", capacity_mt: 150, item: "Marine products", sector: "Pvt" },
  { sno: 48, name: "New India Maritime Agencies 55, Armenian st Chennai-1 CS at Tondiarpet", district: "Kancheepuram", capacity_mt: 750, item: "Multipurpose", sector: "Pvt" },
  { sno: 49, name: "Agri-Marine exports P ltd Ennore coastal high road Chennai-19", district: "Kancheepuram", capacity_mt: 75, item: "Marine products", sector: "Pvt" },
  { sno: 50, name: "Liberty cold storage Ltd, 63/1, Muttukadu road, Neelankarai, chenni-41", district: "Kancheepuram", capacity_mt: 750, item: "Marine products", sector: "Pvt" },
  { sno: 51, name: "New India maritime agencies 55, Armenian St, Chennai-1 CS at Tondiarpet", district: "Kancheepuram", capacity_mt: 400, item: "Marine products", sector: "Pvt" },
  { sno: 52, name: "TNFDC Ltd 67, Greams Road, Chennai-6 Cs at Ennore CS at Adayar", district: "Kancheepuram", capacity_mt: 100, item: "Marine products", sector: "Pub" },
  { sno: 53, name: "Agar & Alginate Laboratories Muttukadu road, Neelankarai, Chennai-41(closed)", district: "Kancheepuram", capacity_mt: 75, item: "Marine products", sector: "Pvt", is_closed: true },
  { sno: 54, name: "Farm SuzzanneP ltd Palavakkam Chennai-41", district: "Kancheepuram", capacity_mt: 200, item: "Marine products", sector: "Pvt" },
  { sno: 55, name: "Blue star foods 4-215A, MGR road Palavakkam Chennai-41", district: "Kancheepuram", capacity_mt: 150, item: "Marine products", sector: "Pvt" },
  { sno: 56, name: "Victoria Marine & Agro exports ltd, 37, Old Mahabalipuram road,Padur, Chennai", district: "Kancheepuram", capacity_mt: 350, item: "marine products", sector: "Pvt" },
  { sno: 57, name: "Overseas marine products D-3.block, DII, Alwarpet Chennai-18 CS at kancheepuram Dt", district: "Kancheepuram", capacity_mt: 400, item: "Marine products", sector: "Pvt" },
  { sno: 58, name: "Cochin sea foods, 4/216 , MGR road, Palavakkam,Chennai-41", district: "Kancheepuram", capacity_mt: 150, item: "Marine products", sector: "Pvt" },
  { sno: 59, name: "Orient marine products P Ltd Manjambakkam, Chennai-600 060", district: "Kancheepuram", capacity_mt: 300, item: "marine products", sector: "Pvt" },
  { sno: 60, name: "Ayshwarya Seafoods Ltd 4/364, Anna Rd,Palavakkam Chennai-41", district: "Kancheepuram", capacity_mt: 150, item: "marine products", sector: "Pvt" },
  { sno: 61, name: "RBT exports 291,Bandikavannor village Ponneri Taluk", district: "Kancheepuram", capacity_mt: 180, item: "marine products", sector: "Pvt" },
  { sno: 62, name: "Balaji sea food exports Ltd 107,Bandikavannor village Sholavaram post Chennai-67", district: "Kancheepuram", capacity_mt: 140, item: "marine products", sector: "Pvt" },
  { sno: 63, name: "Sri sakthi cold storage P ltd 35, Kazhipattur village Padur post Kancheepuram Dist", district: "Kancheepuram", capacity_mt: 400, item: "marine products", sector: "Pvt" },
  { sno: 64, name: "Ocean foods I ltd Padur village Old Mahabalipuram road Chennai-103", district: "Kancheepuram", capacity_mt: 100, item: "marine products", sector: "Pvt" },
  { sno: 65, name: "Westernfarm fresh P Ltd Varadarajapuram Poonamalee Sriperambadur,Chennai", district: "Kancheepuram", capacity_mt: 5475, item: "multipurpose", sector: "Pvt" },
  { sno: 66, name: "Asian marine products p Ltd East coast road, Injambakkam, Chennai-41", district: "Kancheepuram", capacity_mt: 150, item: "marine products", sector: "Pvt" },
  { sno: 67, name: "Oceanic Fisheries Ltd Padanthalmoodu Kanyakumari Distt", district: "Kanyakumari", capacity_mt: 50, item: "Marine Products", sector: "Pvt" },
  { sno: 68, name: "Relish foods P Ltd, 17/9B, Tirunelveli Road, Madhavapuram, Kanyakumari", district: "Kanyakumari", capacity_mt: 75, item: "Marine products", sector: "Pvt" },
  { sno: 69, name: "M.M.Hitech cold storage P ltd, 104, East masi st Madurai-625001", district: "Madurai", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 70, name: "Ayyanar cold storage Madurai-Dindigul NH Ayyankottai Madurai-624221", district: "Madurai", capacity_mt: 206, item: "multipurpose", sector: "Pvt" },
  { sno: 71, name: "Ayyanar cold storage , Dindigul NH road, Ayyankottai, Madurai-624 221", district: "Madurai", capacity_mt: 3200, item: "multipurpose", sector: "Pvt" },
  { sno: 72, name: "Kaveri cold storage Paravai village Madurai-625 402", district: "Madurai", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 73, name: "Farmer brothers & co 33, M.C. Chidambara nadar st, Virudhnagar CS at Madurai", district: "Madurai", capacity_mt: 3500, item: "multipurpose", sector: "Pvt" },
  { sno: 74, name: "M.M.Hi-Tech cold storage P ltd, 104, East Masi st, Madurai-625 001", district: "Madurai", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 75, name: "Tamil nadu coop milk marketing fed. Ltd, Madurai dairy Madurai", district: "Madurai", capacity_mt: 735, item: "milk products", sector: "coop" },
  { sno: 76, name: "Kaveri cold storage 39C/NH, Paravai Village, Madurai-625 019", district: "Madurai", capacity_mt: 3500, item: "Multipurpose", sector: "Pvt" },
  { sno: 77, name: "Ayyanar Cold storage Madurai-Dindigul NH Ayyankottai,Madurai-624221", district: "Madurai", capacity_mt: 4000, item: "Multipurpose", sector: "Pvt" },
  { sno: 78, name: "ADR cold storage, D-24, SIDCO Ind. Estate, Kappalur, Madurai", district: "Madurai", capacity_mt: 2327, item: "multipurpose", sector: "pvt" },
  { sno: 79, name: "Tamil Nadu coop milk marketing fed ltd Ooty dary Ooty", district: "Nilgiris", capacity_mt: 470, item: "milk products", sector: "coop" },
  { sno: 80, name: "Shanmuganathan cold storage P ltd, 95-A, Thiru-Vika nagar, Puthur, Trichy-620 017 (CS at Puthukottai)", district: "Puthukottai", capacity_mt: 2500, item: "multipurpose", sector: "Pvt" },
  { sno: 81, name: "TNFDC Ltd Boat building yard Mandapam 623 518", district: "Ramnathapuram", capacity_mt: 100, item: "Marine products", sector: "Pvt" },
  { sno: 82, name: "Poyilakada fisheries Ltd RS No.38/1235, Nagachi Village, Uchuppudi Ramnad Dist", district: "Ramnathapuram", capacity_mt: 200, item: "Marine products", sector: "Pvt" },
  { sno: 83, name: "Baby marine exports Mandapam Ramnadapuram Dt", district: "Ramnathapuram", capacity_mt: 400, item: "Marine products", sector: "Pvt" },
  { sno: 84, name: "Asvini fisheries Ltd, 10, K. B dasan Road, Chennai-6000 18 (CS at ramanathapuram)", district: "Ramnathapuram", capacity_mt: 300, item: "marine products", sector: "Pvt" },
  { sno: 85, name: "Tamil nadu coop milk marketing fed ltd, Ramanathapuram dairy Ramnad", district: "Ramnathapuram", capacity_mt: 40, item: "milk products", sector: "coop" },
  { sno: 86, name: "Tamil nadu coop milk Marketing Fed Ltd Salem dairy Salem", district: "Salem", capacity_mt: 543, item: "milk products", sector: "coop" },
  { sno: 87, name: "Raj Vignesh cold storage P ltd, 107/5B,Kudalore village Sankan Taluk Salem", district: "Salem", capacity_mt: 2500, item: "multipurpose", sector: "Pvt" },
  { sno: 88, name: "Sri Selvi cold storage P Ltd, 81/6-C, kanagagiri village, Kakapalayam, Salem-637 103", district: "Salem", capacity_mt: 2500, item: "multipurpose", sector: "Pvt" },
  { sno: 89, name: "Atlantic foods Ramalingapuram Salem-636 106", district: "Salem", capacity_mt: 100, item: "Ice creams", sector: "Pvt" },
  { sno: 90, name: "Sri Sachithananda Cold storage,90, east masi St, Madurai-625 001 CS at Theni", district: "Theni", capacity_mt: 3000, item: "multipurpose", sector: "Pvt" },
  { sno: 91, name: "Sri Sundaram Cold storage Allingaram,Periyakulam Rd, Theni", district: "Theni", capacity_mt: 4000, item: "multipurpose", sector: "Pvt" },
  { sno: 92, name: "National dairy devt. Board Ambattur dairy Ambattur", district: "Thiruvallur", capacity_mt: 175, item: "milk products", sector: "coop" },
  { sno: 93, name: "Parwaz food packers 289/2B,Thiruvallur road Alamatti, redhills Chennai-52", district: "Thiruvallur", capacity_mt: 200, item: "marine products", sector: "Pvt" },
  { sno: 94, name: "Saradakripa cold storage P ltd, plot. No.34, Madhavaram Village Ambattur Taluk", district: "Thiruvallur", capacity_mt: 5400, item: "multipurpose", sector: "Pvt" },
  { sno: 95, name: "Renuka Parameswari cold storage P ltd, S.No. 766/1 Near Madhavaram Fly over Madhavaram", district: "Thiruvallur", capacity_mt: 6050, item: "multipurpose", sector: "pvt" },
  { sno: 96, name: "Poorna Vijayasali cold storage ltd, 14, Lotus colony Ist street, Madavaram Chennai-600060", district: "Thiruvallur", capacity_mt: 3100, item: "multipurpose", sector: "Pvt" },
  { sno: 97, name: "SBP cold storage P ltd P H Road, Noombai village, Behind sindhi college Chennai-600077", district: "Thiruvallur", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 98, name: "Tamil nadu coop milk marketing fed. Ltd, Ambattur dairy II Ambattur", district: "Thiruvallur", capacity_mt: 384, item: "milk products", sector: "coop" },
  { sno: 99, name: "Govind cold storageP ltd Ambattur Taluk Thiruvallur", district: "Thiruvallur", capacity_mt: 4150, item: "multipurpose", sector: "Pvt" },
  { sno: 100, name: "Tamil nadu coop milk marketing fed ltd, Ambattur dairy Ambattur", district: "Thiruvallur", capacity_mt: 575, item: "milk products", sector: "coop" },
  { sno: 101, name: "Hatsun foods Company Nallur Village,Ponneri, Thiruvallur Dt", district: "Thiruvallur", capacity_mt: 200, item: "ice creams", sector: "Pvt" },
  { sno: 102, name: "Omshakthy Cold Storage pvt ltd, 1/145,APH road,Vanagaram Chennai-102", district: "Thiruvallur", capacity_mt: 1000, item: "multi purpose", sector: "Pvt" },
  { sno: 103, name: "Somanica foods P ltd 372, Ind.Estate Ambattur, Chennai-58", district: "Thiruvallur", capacity_mt: 45, item: "ice creams", sector: "Pvt" },
  { sno: 104, name: "Tamil nadu coop milk marketing fed ltd, Tirunelveli dairy Tirunelveli", district: "Tirunelveli", capacity_mt: 130, item: "milk products", sector: "coop" },
  { sno: 105, name: "Trichy cold storage P ltd, SIDCO Ind.Estate, Thuvakudi, Trichy.", district: "Trichy", capacity_mt: 5000, item: "multipurpose", sector: "Pvt" },
  { sno: 106, name: "Nila sea foods 166-A, North beach road, Tuticorin- 628 001", district: "Tuticorin", capacity_mt: 50, item: "marine products", sector: "Pvt" },
  { sno: 107, name: "George Maijo & Co, 2-B, Apex Plaza 3, Nungambakkam High Road, Chennai-34 CS at Mandapam", district: "Tuticorin", capacity_mt: 75, item: "Marine products", sector: "Pvt" },
  { sno: 108, name: "Amulya sea foods C-84, SIPCOT Ind. Estate Tuticorin-628 008", district: "Tuticorin", capacity_mt: 200, item: "Marine products", sector: "Pvt" },
  { sno: 109, name: "Amulya sea foods P ltd, C-97 SIPCOT Ind. Estate Tuticorin-628008", district: "Tuticorin", capacity_mt: 200, item: "Marine products", sector: "Pvt" },
  { sno: 110, name: "Diamond seafood exports 3/52,Krishnarajapuram Tuticorin-628002", district: "Tuticorin", capacity_mt: 150, item: "Marine products", sector: "Pvt" },
  { sno: 111, name: "TNFDC Ltd 166A, North beach road, Tuticorin-628001", district: "Tuticorin", capacity_mt: 150, item: "Marine products", sector: "Pub" },
  { sno: 112, name: "Kings international Aqua exports ltd, 51/15B, Muniaswamipuram II st,Kamaraj Salai, Tuticorin-628 101", district: "Tuticorin", capacity_mt: 100, item: "marine products", sector: "Pvt" },
  { sno: 113, name: "Baby marine eastern exports C-75 SIPCOT Ind.Estate Tuticorin-628 008", district: "Tuticorin", capacity_mt: 400, item: "Marine products", sector: "Pvt" },
  { sno: 114, name: "Theva & Co 3/52, Krishnarajapuram Tuticorin-2", district: "Tuticorin", capacity_mt: 200, item: "Marine products", sector: "Pvt" },
  { sno: 115, name: "Nila seas foods P ltd, 137-A, Pudurpandiapuram Tuticorin-628 002", district: "Tuticorin", capacity_mt: 500, item: "marine products", sector: "Pvt" },
  { sno: 116, name: "Amulya sea foods C-96 SIPCOT Ind.Estate Tuticorin-628 008", district: "Tuticorin", capacity_mt: 100, item: "marine products", sector: "Pvt" },
  { sno: 117, name: "Ninans cold storage SIPCOT ind.complex Madathur Tuticorin", district: "Tuticorin", capacity_mt: 5150, item: "Fruits & Vegetable", sector: "Pvt" },
  { sno: 118, name: "Nila cold storage P Ltd 215-B, Pudurpandiapuram Tuticorin", district: "Tuticorin", capacity_mt: 10000, item: "multipurpose", sector: "Pvt" },
  { sno: 119, name: "Kadar Investment & trading Co Ltd, C-51 SIPCOT Ind.Estate, Tuticorin-8", district: "Tuticorin", capacity_mt: 500, item: "Marine products", sector: "Pvt" },
  { sno: 120, name: "Indus cold storage 1/129, Chitheri, Vellore", district: "Vellore", capacity_mt: 1000, item: "multipurpose", sector: "Pvt" },
  { sno: 121, name: "Sri Krishna cold storage 10/2-5, Paranattamangalam Salem", district: "Salem", capacity_mt: 5300, item: "multipurpose", sector: "pvt" },
  { sno: 122, name: "Adi Sakthi cold storage p Ltd, Annur road, Bellady village, Mettupalayam.", district: "Coimbatore", capacity_mt: 5000, item: "multipurpose", sector: "Pvt" },
  { sno: 123, name: "kolar Cold storage Alamaram stop Jedayampalayam village Mettupalayam", district: "Coimbatore", capacity_mt: 4500, item: "multipurpose", sector: "pvt" },
  { sno: 124, name: "Palamudir cold storgae Chinnayampalayam Coimbatore", district: "Coimbatore", capacity_mt: 500, item: "multipurpose", sector: "pvt" },
  { sno: 125, name: "Ranga Lalitha Cold Storage, 500, Main Road, Shevepet, salem-636 002", district: "Salem", capacity_mt: 2000, item: "multipurpose", sector: "Pvt" },
  { sno: 126, name: "Vidya Bharathi cold storage, 152/34, G N T Road, Madhavaram, chennai", district: "Thiruvallur", capacity_mt: 5500, item: "mutipurpose", sector: "pvt" },
  { sno: 127, name: "Garden Fresh cold storage, SF 89, Karisalpatti, Allampatti PO, Thirumangalam", district: "Madurai", capacity_mt: 2500, item: "multipurpose", sector: "pvt" },
  { sno: 128, name: "Sri Ayyappa Hitech cold storage Ltd, 277/2, Jadayampalayam, Annur road, Mettupalayam, Coimbatore", district: "Coimbatore", capacity_mt: 5000, item: "multipurpose", sector: "pvt" },
  { sno: 129, name: "Ranga Lalitha cold storage, 500, main road, Shevapet, salem-636 002", district: "Salem", capacity_mt: 2000, item: "multipurpose", sector: "pvt" },
  { sno: 130, name: "EmpeeBee Exports&imports, 109/3, Noombal Village, Ambattoor", district: "Thiruvallur", capacity_mt: 3000, item: "multipurpose", sector: "pvt" },
  { sno: 131, name: "Fazil cold storage, SF 68, Punganur village, Dindigul road, Trichy.", district: "Trichy", capacity_mt: 4400, item: "multipurpose", sector: "pvt" },
  { sno: 132, name: "Elumalai Cold Storage P Ltd, 31/1A, Padikasipatti village, Rajapalayam,Virudhnagar,", district: "Virudhnagar", capacity_mt: 2320, item: "multipurpose", sector: "pvt" },
  { sno: 133, name: "Sree Bishnu Potato cold storageLtd,SF 464/3,Bellathi village, Mettupalayam", district: "Coimbatore", capacity_mt: 7000, item: "multipurpose", sector: "pvt" },
  { sno: 134, name: "Devraj Agro Industries 103, women ind. Park, Thirumullaivoyal, Ambattor", district: "Thiruvallur", capacity_mt: 5760, item: "multipurpose", sector: "pvt" },
  { sno: 135, name: "Kolar cold storage 238/1, Jadampalayam village Mettupalayam.", district: "Coimbatore", capacity_mt: 4250, item: "multipurpose", sector: "pvt" },
  { sno: 136, name: "Arunachala cold storage 219/1A-4, Puzhal Vill, Vadaperumbakkam, Ambattur.", district: "Thiruvallur", capacity_mt: 5300, item: "multipurpose", sector: "pvt" }
];

export const REAL_COLD_STORAGES_TN = rawData.map((item, idx) => {
  const distCoord = DISTRICT_COORDS[item.district] || { lat: 11.0, lng: 78.0 };
  
  // Deterministic slight spatial offset so markers don't overlap completely
  const latOffset = ((idx * 17) % 60 - 30) * 0.0035;
  const lngOffset = ((idx * 23) % 60 - 30) * 0.0035;

  const dailyKg = item.capacity_mt * 1000;
  // Simulated booked ratio between 35% and 85%
  const bookedPercent = item.is_closed ? 1.0 : (35 + (idx * 13) % 50) / 100;
  const bookedKg = Math.round(dailyKg * bookedPercent);
  
  let status = item.is_closed ? 'CLOSED' : 'OPEN';
  if (!item.is_closed && bookedPercent >= 0.85) status = 'HIGH_LOAD';

  return {
    id: `cs-tn-${item.sno}`,
    code: `CS-TN-${item.sno < 10 ? '00' + item.sno : item.sno < 100 ? '0' + item.sno : item.sno}`,
    name: item.name,
    latitude: Number((distCoord.lat + latOffset).toFixed(6)),
    longitude: Number((distCoord.lng + lngOffset).toFixed(6)),
    address: `${item.name}, ${item.district} District, Tamil Nadu`,
    district: item.district,
    state: 'Tamil Nadu',
    status: status,
    daily_capacity_kg: dailyKg,
    booked_capacity_kg: bookedKg,
    capacity_mt: item.capacity_mt,
    item_type: item.item,
    sector: item.sector,
    active_counters: Math.max(2, (item.sno % 5) + 1),
    avg_processing_minutes: 10 + (item.sno % 8),
    operational_start: '08:00 AM',
    operational_end: '06:00 PM',
    queue_count: Math.round((dailyKg - bookedKg) / 3000) % 25,
    today_procured_kg: Math.round(bookedKg * 0.6),
    contact_phone: `+91 94440 ${10000 + item.sno}`
  };
});
